# Queries para criação do banco de dados de Conflitos Belicos para ACH2004 em Mysql
#
# Mycaelli Cerqueira de Lima - 10723562

CREATE SCHEMA conflitos_belicos;
USE conflitos_belicos;

CREATE TABLE TRAFICANTE_DE_ARMAS (
    Traficante_ID INT NOT NULL,
    Nome_Traficante VARCHAR(255) NOT NULL,    
    PRIMARY KEY (Traficante_ID)
);


CREATE TABLE ARMA (
    Arma_ID INT NOT NULL, 
    Nome VARCHAR(255) NOT NULL,  
    Tipo_Arma VARCHAR(255) NOT NULL,   
    Capacidade_Destrutiva INT NOT NULL,
    Traficante_ID INT NOT NULL, 
    Quantidade_Total INT NOT NULL,
    PRIMARY KEY (Arma_ID, Nome)
);

CREATE TABLE FORNECE_ARMAS (  
    Traficante_ID INT NOT NULL,  
    ID_Grupo  INT NOT NULL, 
    Quantidade INT NOT NULL,
    Arma_ID INT NOT NULL, 
    PRIMARY KEY (Nome_Traficante, ID_Grupo)
);

CREATE TABLE CHEFE_MILITAR (   
    ID_Chefe_Militar INT NOT NULL, 
    Hierarquia VARCHAR(255) NOT NULL, 
    Lider_Politico VARCHAR(255) NOT NULL, 
    PRIMARY KEY (ID_Chefe_Militar)
);

CREATE TABLE LIDER_POLITICO (   
    Nome VARCHAR(255) NOT NULL, 
    Apoios VARCHAR(255) NOT NULL,     
    ID_Grupo INT NOT NULL,
    PRIMARY KEY (Nome, ID_Grupo)
);

# testando uma tabelas
CREATE TABLE CHEFEM_LIDERA(
    ID_Divisao INT NOT NULL,
    ID_Grupo INT NOT NULL,
    ID_Chefe_Militar INT NOT NULL,
    PRIMARY KEY (ID_Divisao, ID_Grupo, ID_Chefe_Militar)
);

CREATE TABLE DIALOGA (  
    Lider_Politico VARCHAR(255) NOT NULL,
    ID_Organizacao_Mediadora INT NOT NULL,
    PRIMARY KEY(Lider_Politico, ID_Organizacao_Mediadora)
);

CREATE TABLE ORGANIZACAO_MEDIADORA (
    ID_Organizacao_Mediadora INT NOT NULL,
    Nome VARCHAR(255) NOT NULL, 
    Tipo VARCHAR(255) NOT NULL,
    Organizacao_Depende VARCHAR(255),
    PRIMARY KEY (ID_Organizacao_Mediadora)
);

CREATE TABLE GRUPO_ARMADO (   
    ID_Grupo INT NOT NULL,   
    Nome VARCHAR(255) NOT NULL,  
    Baixas_Totais INT NOT NULL,
    PRIMARY KEY (ID_Grupo)
);


CREATE TABLE DIVISAO (   
    ID_Divisao INT NOT NULL,
    ID_Grupo INT NOT NULL,
    Baixas INT NOT NULL, 
    Barcos INT NOT NULL, 
    Homens INT NOT NULL, 
    Tanques INT NOT NULL, 
    Aviões INT NOT NULL,    
    Contador INT NOT NULL,
    PRIMARY KEY (ID_Divisao, ID_Grupo)
);

CREATE TABLE CONFLITO (       
    ID_Conflito INT NOT NULL,          
    Mortos INT NOT NULL, 
    Feridos INT NOT NULL, 
    Nome VARCHAR(255) NOT NULL,  
    Contador INT NOT NULL,
    Tipo_Conflito INT NOT NULL,
    PRIMARY KEY (ID_Conflito)
);

CREATE TABLE PAIS_AFETADO(
    Pais VARCHAR(255) NOT NULL,
    ID_Conflito INT NOT NULL,
    PRIMARY KEY(Pais, ID_Conflito)
);

CREATE TABLE GRUPO_CONFLITO (
    ID_Conflito INT NOT NULL,
    ID_Grupo INT NOT NULL,
    Data_Saida DATE NOT NULL,
    Data_Entrada DATE NOT NULL,
    PRIMARY KEY(ID_Conflito, ID_Grupo)
);

CREATE TABLE ORGANIZACAO_CONFLITO (
    ID_Conflito INT NOT NULL,
    ID_Organizacao_Mediadora INT NOT NULL,
    Data_Saida DATE NOT NULL,
    Data_Entrada DATE NOT NULL,
    Pessoas INT NOT NULL, 
    Tipo_Ajuda VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_Conflito, ID_Organizacao_Mediadora)
);

CREATE TABLE CONFLITO_RELIGIOSO(
    ID_Conflito INT NOT NULL,
    Religiao VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_Conflito, Religiao)
);

CREATE TABLE CONFLITO_TERRITORIAL (  
    ID_Conflito INT NOT NULL,   
    Regiao VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_Conflito, Regiao)
);


CREATE TABLE CONFLITO_ECONOMICO (  
    ID_Conflito INT NOT NULL,   
    Materia_Prima VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_Conflito, Materia_Prima)
);


CREATE TABLE CONFLITO_RACIAL (  
    ID_Conflito INT NOT NULL,   
    Etnia VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_Conflito, Etnia)
);


# Criar FOREIGN KEYs

ALTER TABLE ARMA ADD CONSTRAINT fk_Traficante_ID_1 FOREIGN KEY (Traficante_ID) REFERENCES TRAFICANTE_DE_ARMAS(Traficante_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE FORNECE_ARMAS ADD CONSTRAINT fk_Traficante_ID_2 FOREIGN KEY (Traficante_ID) REFERENCES TRAFICANTE_DE_ARMAS(Traficante_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FORNECE_ARMAS ADD CONSTRAINT fk_ID_Grupo_3 FOREIGN KEY (ID_Grupo) REFERENCES GRUPO_ARMADO(ID_Grupo) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FORNECE_ARMAS ADD CONSTRAINT fk_Arma_ID_4 FOREIGN KEY (Arma_ID) REFERENCES ARMA(Arma_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CHEFE_MILITAR ADD CONSTRAINT fk_Lider_Politico_5 FOREIGN KEY (Lider_Politico) REFERENCES LIDER_POLITICO(Nome) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE LIDER_POLITICO ADD CONSTRAINT fk_ID_Grupo_6 FOREIGN KEY (ID_Grupo) REFERENCES GRUPO_ARMADO(ID_Grupo) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CHEFEM_LIDERA ADD CONSTRAINT fk_ID_Divisao_7 FOREIGN KEY (ID_Divisao) REFERENCES DIVISAO(ID_Divisao) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CHEFEM_LIDERA ADD CONSTRAINT fk_ID_Grupo_8 FOREIGN KEY (ID_Grupo) REFERENCES GRUPO_ARMADO(ID_Grupo) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CHEFEM_LIDERA ADD CONSTRAINT fk_ID_Chefe_Militar_9 FOREIGN KEY (ID_Chefe_Militar) REFERENCES CHEFE_MILITAR(ID_Chefe_Militar) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DIALOGA ADD CONSTRAINT fk_Lider_Politico_10 FOREIGN KEY (Lider_Politico) REFERENCES LIDER_POLITICO(Nome) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DIALOGA ADD CONSTRAINT fk_ID_Organizacao_Mediadora_11 FOREIGN KEY (ID_Organizacao_Mediadora) REFERENCES ORGANIZACAO_MEDIADORA(ID_Organizacao_Mediadora) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DIVISAO ADD CONSTRAINT fk_ID_Grupo_12  FOREIGN KEY (ID_Grupo) REFERENCES GRUPO_ARMADO(ID_Grupo) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PAIS_AFETADO ADD CONSTRAINT fk_ID_Conflito_13  FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE GRUPO_CONFLITO ADD CONSTRAINT fk_ID_Conflito_14  FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE GRUPO_CONFLITO ADD CONSTRAINT fk_ID_Grupo_14  FOREIGN KEY (ID_Grupo) REFERENCES GRUPO_ARMADO(ID_Grupo) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ORGANIZACAO_CONFLITO ADD CONSTRAINT fk_ID_Conflito_16  FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ORGANIZACAO_CONFLITO ADD CONSTRAINT fk_ID_Organizacao_Mediadora_17  FOREIGN KEY (ID_Organizacao_Mediadora) REFERENCES ORGANIZACAO_MEDIADORA(ID_Organizacao_Mediadora) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONFLITO_RELIGIOSO ADD CONSTRAINT fk_ID_Religiao_18  FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONFLITO_TERRITORIAL ADD CONSTRAINT fk_ID_Regiao_19 FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONFLITO_ECONOMICO ADD CONSTRAINT fk_ID_Economico_20  FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONFLITO_RACIAL ADD CONSTRAINT fk_ID_Racial_21  FOREIGN KEY (ID_Conflito) REFERENCES CONFLITO(ID_Conflito) ON DELETE CASCADE ON UPDATE CASCADE;
